GaloisInc/what4

what4/src/What4/Solver/Boolector.hs
The Boolector devs (very) recently added all of the features we need to support
an online backend (including the global scoping option).  This commit adds the
necessary interface bits to use Boolector in online mode.
=> Add an online backend for Boolector

what4/src/What4/Expr/Builder.hs, what4/src/What4/Expr/VarIdentification.hs
Compare performance results of this PR against the hashtable-linear PR #18.
=> Change hashtable implementation to basic from cuckoo.

what4/src/What4/Protocol/SMTWriter.hs, what4/test/ExprBuilderSMTLib2.hs
=> Declare struct types occuring in the bound variables

what4/doc/bvdomain.cry, what4/src/What4/Utils/BVDomain.hs
=> Fix bugs in abstract bitvector domain operations `sdiv` and `srem`.

what4/src/What4/Expr/Builder.hs
=> Fix a pretty printer typo for real multiplication

what4/src/What4/Protocol/Online.hs, what4/src/What4/Protocol/SMTLib2.hs, what4/src/What4/Protocol/SMTWriter.hs, what4/src/What4/Solver.hs, what4/src/What4/Solver/Boolector.hs, what4/src/What4/Solver/CVC4.hs, what4/src/What4/Solver/DReal.hs, what4/src/What4/Solver/STP.hs, what4/src/What4/Solver/Yices.hs, what4/src/What4/Solver/Z3.hs, what4/test/AdapterTest.hs, what4/test/OnlineSolverTest.hs, what4/what4.cabal
Some updates so What4 solver integration, mostly to bring STP, dReal, and Boolector support up-to-date with the current status of those solvers.
=> Solver updates

what4/test/AdapterTest.hs, what4/test/OnlineSolverTest.hs, what4/what4.cabal
Misc updates to solver tests for timeouts, reporting, and allowing CI to skip dReal solver tests.
=> solver test updates

what4/what4.cabal
Builds fine and all tests pass here.
=> Allow th-abstraction 0.4

what4/src/What4/SWord.hs
The reason for adding these functions is to improve the round-tripping between saw-core and what4: The what4 `bvZext` and `bvSext` operations map to the saw-core functions `bvUExt` and `bvSExt`. However, in the reverse direction, the saw-core-what4 backend doesn't implement those as primitives; instead they are defined in terms of concatenation and conditionals. So they don't actually map back onto the same what4 operations.
Adding these operations to the `SWord` module makes it possible to have a 1-to-1 mapping between bitvector primitives in what4 and saw-core.
=> Add functions `bvZext` and `bvSext` to module `What4.SWord`.

what4/what4.cabal
=> Allow versions 5.0

what4/src/What4/SWord.hs
Previously, these would panic if a 0-bit slice was requested.  Instead,
they now return the distinguished `ZBV` 0-length bitvector value.
Minor other tweaks.
Fixes #113
=> Relax the failure conditions for `bvSliceBE` and `bvSliceLE`.

what4/src/What4/Protocol/SMTWriter.hs, what4/what4.cabal
This significantly speeds up some workloads.
=> Inline the definitions of some utility functions.

what4/README.md, what4/src/What4/Solver/Boolector.hs
=> Remove obsolete boolector command-line option

what4/src/What4/Concrete.hs, what4/src/What4/Interface.hs
I found this to be useful as part of a debugging effort for GaloisInc/crucible#828.
Fixes #137.
=> Add ConcreteFloat constructor

.github/workflows/gen_matrix.pl, .github/workflows/test.yml, README.md, what4/CHANGES.md, what4/README.md, what4/doc/implementation.md, what4/src/What4/Expr/AppTheory.hs, what4/src/What4/ProblemFeatures.hs, what4/src/What4/Protocol/SMTLib2.hs, what4/src/What4/Protocol/SMTLib2/Syntax.hs, what4/src/What4/Solver.hs, what4/src/What4/Solver/Boolector.hs, what4/src/What4/Solver/CVC4.hs, what4/src/What4/Solver/CVC5.hs, what4/test/AdapterTest.hs, what4/test/ExprBuilderSMTLib2.hs, what4/test/OnlineSolverTest.hs, what4/what4.cabal
Adding cvc5 support
Fixes #202
=> Adding support for cvc5

what4-transition-system/src/What4/TransitionSystem.hs
This PR generalizes the `TransitionSystem` type to include a list of inputs. This is mainly to facilitate a corresponding change to `language-sally`, to support Sally's input variables.
This is a breaking change, but I'm not sure if there are any downstream users to be broken at the moment - if there are, I'd be happy to fix them, so any pointers in that direction would be appreciated!
=> Add support for transition system inputs

what4/CHANGES.md, what4/README.md, what4/src/What4/Serialize/FastSExpr.hs, what4/src/What4/Serialize/Log.hs, what4/src/What4/Serialize/Normalize.hs, what4/src/What4/Serialize/Parser.hs, what4/src/What4/Serialize/Printer.hs, what4/src/What4/Serialize/SETokens.hs, what4/src/What4/Utils/Serialize.hs, what4/test/SerializeTestUtils.hs, what4/test/SerializeTests.hs, what4/test/SymFnTests.hs, what4/what4.cabal
This code provides mechanisms to serialize and deserialize what4 terms using a
syntax that is (almost entirely) compatible with smtlib.
Fixes #104
=> Merge what4-serialize into what4 core

what4/what4.cabal
=> Bump text dependency

what4-transition-system/what4-transition-system.cabal, what4/CHANGES.md, what4/what4.cabal
Towards a resolution for #261.
=> 1.6 release prep

what4/src/What4/Expr/GroundEval.hs
My intended use-case is to make use of `ppExpr` to pretty-print ground expressions. However, I think this is a generally useful function in any case.
=> Inject ground values back into symbolic expressions

.github/workflows/test.yml
=> ci: Small improvements

.github/workflows/gen_matrix.pl, .github/workflows/lint.yml, .github/workflows/test.yml
=> ci: Pin OS version to `ubuntu-24.04`

what4-abc/src/What4/Solver/ABC.hs, what4-blt/src/What4/Solver/BLT.hs
=> `what4-{abc,blt}`: Fix the build after `ConjMap`'s introduction

what4/what4.cabal
=> Allow building with `time-1.14.*`
