GaloisInc/what4

what4/src/What4/Expr/Builder.hs
In particular, this allows the evaluation function passed to
`idxCacheEval` to be in a more general monad.
=> Generalize the type of IdxCache functions

what4/src/What4/Expr/Builder.hs, what4/test/GenWhat4Expr.hs
Fixes #11
Remove the restriction on bit-widths in the random term generator.
=> Add tests for overshifting in `bvShl`, `bvLshr` and `bvAshr`

what4/src/What4/Expr/Builder.hs
This avoids a major performance regression with the hash table
implementation now used by parameterized-utils in module
`Data.Parameterized.HashTable`. (see GaloisInc/saw-script#674)
=> Change `IdxCache` type to use `Data.Parameterized.Map`.

what4/src/What4/SWord.hs, what4/what4.cabal
This interface is intended to be used for the new Cryptol/What4 backend, and may eventually replace the similar SAWCore/What4 interface.
=> SWord interface for words of dynamically-known width

.travis.yml, what4-abc/src/What4/Solver/ABC.hs, what4/doc/arithdomain.cry, what4/doc/bitsdomain.cry, what4/doc/bvdomain.cry, what4/doc/xordomain.cry, what4/src/What4/Expr/Builder.hs, what4/src/What4/Expr/WeightedSum.hs, what4/src/What4/Protocol/SMTWriter.hs, what4/src/What4/Utils/Arithmetic.hs, what4/src/What4/Utils/BVDomain.hs, what4/src/What4/Utils/BVDomain/Arith.hs, what4/src/What4/Utils/BVDomain/Bitwise.hs, what4/src/What4/Utils/BVDomain/XOR.hs, what4/test/BVDomTests.hs, what4/what4.cabal
The bitvector abstract domain has been split into two subdomains: one for dealing with arithmetic operations and one for dealing with bitwise operations.  We attempt to minimize information loss by only shifting between the two modes when necessary.  The Cryptol specification of the these domains is likewise split between the two modes.
I've added a new test suite specifically to test the same correctness assertions as found in the Cryptol specification.  This exposed bugs in the `sdiv` and `srem` operations, where the implementations did not meet the specification.
There is also a third domain optimized for performing XOR operations.  It is essentially isomorphic to the bitwise domain, but requires fewer operations to compute XOR.  It is specifically for use in the bitwise XOR semi-ring. …
=> Bitvector abstract domain enhancements

what4/src/What4/Utils/BVDomain.hs, what4/src/What4/Utils/BVDomain/Arith.hs, what4/src/What4/Utils/BVDomain/Bitwise.hs, what4/test/BVDomTests.hs
Default to using the arithmetic mode so that when we union together
a collection of consecutive singleton values, we get a precise arithmetic
interval.  Add a test to the test suite to check for this property.
=> Tweak the BVDomain to handle common cases better

what4/src/What4/Protocol/SMTLib2.hs
GHC 8.4 haddock does not support comments on individual fields of an
ADT.  This particular structure is internal only and lacks general
description haddocks, so simply converting these from haddock comments
to normal comments resolves this issue.
=> Make ADT field comments normal, not haddock for internal structure.

what4/src/What4/Protocol/SMTWriter.hs
As discussed in #44 , those changes will allow implementing language-sally by leveraging What4's SMTWriter.
Speaking of which, the language-sally package will need to depend on a version of what4 that exposes those functions. Does this warrant a new minor version number? Should I just hardcode this commit number until what4 is ready for a version bump?
EDIT: Come to think about it, I will be using language-sally within crucible and can just use a submodule to pinpoint the commit for the time being.
=> Expose some SMT collector operations in SMTWriter.

what4-abc/src/What4/Solver/ABC.hs, what4/src/What4/Expr/AppTheory.hs, what4/src/What4/Expr/Builder.hs, what4/src/What4/Expr/GroundEval.hs, what4/src/What4/Interface.hs, what4/src/What4/Protocol/SMTWriter.hs, what4/test/ExprBuilderSMTLib2.hs
Add `realTrunc` and `realRoundEven` operations to fill out the standard rounding modes.
Add test cases that prove the rounding operations satisfy their specifications.
Fixes #46
=> Real rounding modes

what4/src/What4/Expr/WeightedSum.hs, what4/src/What4/Utils/BVDomain.hs, what4/src/What4/Utils/BVDomain/Arith.hs, what4/test/BVDomTests.hs, what4/test/ExprBuilderSMTLib2.hs
Currently, `bvSub` or any other operation that introduces a negative coefficient in the semi-ring makes the abstract domain go to `BVAny`.
cc @travitch
=> Fix use of BVDomain.Arith.scale.

what4/src/What4/Protocol/Online.hs, what4/src/What4/Solver/Adapter.hs, what4/src/What4/Utils/HandleReader.hs
Some minor changes to support Cryptol.  The `smokeTest` simply performs a trivial query to verify that we can communicate with a particular solver, and some minor changes to the exception-handling stack allow more graceful interruption.
=> Adapter enhancements

what4/src/What4/Interface.hs, what4/test/ExprsTest.hs, what4/test/IteExprs.hs, what4/what4.cabal
Adds basic test cases for:
* intAbs
* intDiv
* intMod
* structIte
* stringEmpty
* realToInteger
* bvToNat
* bvToInteger
* sbvToInteger
* predToBV
* integerToBV
I also had to extend `asConcrete` with a case for structs. I tried to also add one for arrays but gave up when I realize there's something going on with arrays that I don't understand. I also found and fixed one documentation bug when testing `intDiv`.
There's still a lot of interesting cases in many of these functions but constructing tests that get full coverage is tricky. We deemed it more important to go for breadth than depth at this time.
=> Add basic test cases for more of the Builder interface

what4/src/What4/Protocol/Online.hs, what4/src/What4/Protocol/SMTLib2.hs, what4/src/What4/Solver/CVC4.hs, what4/src/What4/Solver/Yices.hs, what4/src/What4/Solver/Z3.hs
Allows clients using the started solver (e.g. crucible) to access the
timeout value.
Updates each solver's startSolverProcess to get the solver's goal
timeout configuration value (if any) to set the solverGoalTimeout
field.
This is support for fixing crucible issue #439, as well as providing
the ability to timeout other solvers that don't have native timeout
support (e.g. boolector, see what4 issue #16), albeit in a cruder,
heavy-handed, yet implacable manner.
=> [what4] Provide SolverGoalTimeout as part of SolverProcess.

what4/src/What4/Config.hs, what4/src/What4/Expr/Builder.hs, what4/src/What4/Protocol/Online.hs, what4/src/What4/Protocol/SMTWriter.hs, what4/src/What4/Solver/Adapter.hs
Audit all uses of IORefs in What4 and replace with with atomic primitives where necessary, or document when they require external synchronization.
=> Audit IORefs

what4/src/What4/Interface.hs
Address https://github.com/GaloisInc/what4/issues/72.
I believe Brian's concern about "undefined" is addressed in the documentation for the `IsExprBuilder` class itself, but perhaps there is a way to make it more explicit in the various functions that have certain conditional undefined behavior.
=> Fixes documentation for intDiv in What4.Interface

what4/src/What4/Expr/App.hs, what4/src/What4/Expr/Builder.hs, what4/src/What4/Expr/VarIdentification.hs, what4/src/What4/Protocol/SMTWriter.hs, what4/src/What4/Protocol/VerilogWriter/Backend.hs
module, and change the traversal operation on `App` so that it
doesn't descend into the body of defined functions.
=> Push the definition of the `Expr` datatype into the `What4.Expr.App`

.github/workflows/test.yml, what4/README.md, what4/solverBounds.config, what4/src/What4/Protocol/SMTLib2.hs, what4/src/What4/Utils/Versions.hs, what4/test/ExprBuilderSMTLib2.hs, what4/what4.cabal
This might be a good time to add realistic version bounds to this part of the code.  Do we have more up-to-date expected versions than are currently in the What4 readme @kquick? Maybe we could put those someplace machine-readable and use TH to automatically import them into this module.
=> Fix compile with versions >= 4.0

what4-abc/src/What4/Solver/ABC.hs, what4/src/What4/Expr/App.hs, what4/src/What4/Expr/AppTheory.hs, what4/src/What4/Expr/Builder.hs, what4/src/What4/Expr/GroundEval.hs, what4/src/What4/Expr/Simplify.hs, what4/src/What4/Expr/VarIdentification.hs, what4/src/What4/Interface.hs, what4/src/What4/InterpretedFloatingPoint.hs, what4/src/What4/Protocol/SMTLib2.hs, what4/src/What4/Protocol/SMTWriter.hs, what4/src/What4/Protocol/VerilogWriter/Backend.hs, what4/src/What4/SFloat.hs, what4/src/What4/Solver/Yices.hs, what4/src/What4/Utils/FloatHelpers.hs, what4/test/ExprBuilderSMTLib2.hs, what4/test/TestTemplate.hs, what4/what4.cabal
Use the `libBF` library to implement concrete floating-point ground evaluation and constant folding.
This is especially a tricky area to get right, so I've implemented a new testing technique using "expression templates."   These are fragments of syntax containing variables at base types.  We can enumerate an interesting collection of these templates and use them to generate test cases.  For each test case, we will chose random concrete values for the variables and evaluate the syntax in a variety of ways and test that they agree.  In particular, we can ask solvers to act as computational oracles and verify that our ground evaluation agrees with their theory.
=> Concrete floats

what4/src/What4/Expr/Builder.hs, what4/src/What4/Interface.hs
I think the only way to access a `SymAnnotation` embedded in a term is with a traversal. My hope is that the addition of this function makes the annotations API a bit more flexible.
=> Add "getAnnotation" to project SymAnnotations from SymExprs

what4/src/What4/Expr/Builder.hs
I was encountering a case where this rule was exploding performance, so I added a check for constant branches in a manner similar to other rules. I'm unsure if this is the right thing to do in general - in the longer term, it might be neat to have some way of selectively enabling/disabling rules.
=> Avoid loss of sharing when pushing bitvector equality under conditional

.github/workflows/test.yml, what4-abc/what4-abc.cabal, what4-blt/what4-blt.cabal, what4/src/What4/Concrete.hs, what4/src/What4/Utils/AnnotatedMap.hs, what4/src/What4/Utils/Word16String.hs, what4/what4.cabal
Also uses common stanzas in the cabal file which reduces duplication and makes version updates (especially for test modules) easier.
=> Update cabal version, add some warnings, fix some warnings.

what4/src/What4/Expr/Simplify.hs, what4/src/What4/Expr/WeightedSum.hs
These don't seem to be needed, unless you'd like them to remain to impart intent.
=> Remove a couple of HashableF constraints not explicitly needed.

what4/src/What4/Protocol/Online.hs, what4/src/What4/Protocol/SMTLib2.hs, what4/test/ExprBuilderSMTLib2.hs
These don't seem to be needed, unless they should remain to indicate intent.
=> Remove a couple of SMTReadWriter constraints.

.github/workflows/test.yml, what4/src/What4/Interface.hs, what4/src/What4/Protocol/Online.hs, what4/src/What4/Protocol/SMTLib2.hs, what4/src/What4/Solver/DReal.hs, what4/src/What4/Solver/Yices.hs, what4/what4.cabal
Partial fields are the situation where an ADT is defined with record
syntax.  The field accessors are of type `ADT -> field`, but the field
is only valid for one constructor of the ADT, so proper usage requires
matching on the constructor before using field accessors, and omitting
this matching can lead to invalid accesses.
This change modifies the only use of this in What4 to ensure that the
Record types are not ADT's and vice-versa.
=> Remove use of partial fields and add warning.

what4/src/What4/Protocol/VerilogWriter.hs, what4/src/What4/Protocol/VerilogWriter/AST.hs, what4/test/AdapterTest.hs
This adds support for generating Verilog modules wiht multiple outputs by allowing the user to pass multiple What4 expressions into the Verilog generation functions.
=> Support Verilog modules with multiple outputs

what4/src/What4/Protocol/VerilogWriter/ABCVerilog.hs
This code accidentally included Cryptol type annotations in the Verilog output (because the `bv-sized` pretty-printer includes them). Hilariously, we didn't detect this because ABC can still correctly read the result due to its very permissive parser that skips over things it doesn't understand. Attempting to load files containing rotates into Yosys, which includes a stricter Verilog parser, uncovered the error.
=> Fix bug in printing Verilog rotations for ABC

what4/src/What4/Expr/GroundEval.hs
Use 'mzero' instead of throwing an exception in
'evalGroundNonceApp'. This will be caught and thrown by
'evalGroundExpr', but with a different error message.
=> Avoid spurious failure when grounding NonceApps

what4-abc/src/What4/Solver/ABC.hs, what4-blt/src/What4/Solver/BLT.hs
This updates `what4-{abc,blt}` to use the new `SolverStartSATQueryRec` and `SolverEndSATQueryRec` data types introduced in #111.
Fixes #119.
=> Adapt what4-{abc,blt} to SolverEndSATQuery changes

what4/src/What4/Protocol/VerilogWriter.hs, what4/src/What4/Protocol/VerilogWriter/ABCVerilog.hs, what4/src/What4/Protocol/VerilogWriter/AST.hs, what4/src/What4/Protocol/VerilogWriter/Backend.hs, what4/test/AdapterTest.hs
This makes it possible for the client of the Verilog writer to specify that a specific set of variables should appear in the module input list in a specific order. This makes it so that the order agrees with what the counterexample processor in SAW expects, and makes Verilog modules intended for use elsewhere able to have inputs that appear in the same order as in a Cryptol or SAWCore function. Previously, inputs were ordered according to their occurrence in the term being exported.
Makes progress in moving away from String along the way.
=> Support client-provided Verilog input lists

.github/workflows/test.yml, what4-abc/what4-abc.cabal, what4-blt/what4-blt.cabal, what4-transition-system/what4-transition-system.cabal, what4/src/What4/Expr/App.hs, what4/src/What4/Protocol/SMTLib2/Response.hs, what4/src/What4/Protocol/SMTWriter.hs
This contains a variety of tweaks needed to make `what4`, `what4-abc`, `what4-blt`, and `what4-transition-system` build warning-free on GHC 9.0:
* GHC's constraint solver now solves constraints in each top-level group sooner (see [here](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0?version_id=5fcd0a50e0872efb3c38a32db140506da8310d87#the-order-of-th-splices-is-more-important)). This affects `what4`'s `What4.Expr.App` module, as it separates top-level groups with a Template Haskell `$(return [])` splice. The previous location of this splice made it so that the TH-generated instances in that module (e.g., the `TraversableFC` instance for `App`) were not available to any code before the splice, resulting in type errors when compiled with GHC 9.0.
I implemented a fairly involved fix …
=> Support building with GHC 9.0

what4/src/What4/SWord.hs
When using the SWord module for dynamically-sized words, one has to
match the sizes of shift operations before passing them down to the
main representation code. When the shift amount has a larger bit-width
than the word to be shifted, a range reduction is required so the
truncation of the shift amount still gets the correct result. Previously,
this reduction was being done incorrectly by computing a `max` instead
of a `min`.
Fixes #126
=> Fix incorrect range reduction code in SWord shifts

what4/src/What4/Expr/Builder.hs, what4/src/What4/Interface.hs, what4/src/What4/Utils/AbstractDomains.hs, what4/src/What4/Utils/StringLiteral.hs
Previously, the string index-of and substring functions were
underspecified, whereas the SMTLib theory for these functions
determines precicely their result on out-of-bounds inputs.
Here, we faithfully implement those semantics.
Fixes #103
=> Faithfully implement the semantics of some string operations

what4/src/What4/Solver/Yices.hs
Now, when the `yicesEnableMCSat` option is enabled, the `useNonlinearArithmetic` problem feature will be allowed.
Closes #133.
=> Make yicesEnableMCSat -> non-linear feature

what4/what4.cabal
Fixes test failure when running with the hackage tarball:
```
Test suite solver_parsing_tests: RUNNING...
solver_parsing_tests: test/responses: getDirectoryContents:openDirStream: does not exist (No such file or directory)
Test suite solver_parsing_tests: FAIL
```
=> Include test/responses in hackage tarball

.github/workflows/test.yml, what4/doc/implementation.md, what4/src/What4/Config.hs, what4/src/What4/Protocol/Online.hs, what4/src/What4/Protocol/SMTLib2.hs, what4/src/What4/Protocol/SMTLib2/Response.hs, what4/src/What4/Protocol/SMTWriter.hs, what4/src/What4/Solver.hs, what4/src/What4/Solver/Boolector.hs, what4/src/What4/Solver/CVC4.hs, what4/src/What4/Solver/STP.hs, what4/src/What4/Solver/Yices.hs, what4/src/What4/Solver/Z3.hs, what4/src/What4/Utils/Process.hs, what4/test/AdapterTest.hs, what4/test/ExprBuilderSMTLib2.hs, what4/test/OnlineSolverTest.hs, what4/test/TestTemplate.hs, what4/test/responses/err-behav-unrec.exp, what4/test/responses/minisat_verbose_success.strict.exp, what4/test/responses/rsnunk-bad.exp, what4/what4.cabal
Updates various solver tests and adds better timeout management.
* Running `cabal test` will only ignore tests for missing solvers unless `CI_TEST_LEVEL` is set and not `0`.  This allows easy development with whatever solver is available in the development environment, but ensures that solvers are present and all tests pass in the CI process.
* Some solvers do not provide the ability to add per-goal timeouts.  Other solvers have some difficulty in honoring that timeout even if it is supported.  This PR adds a "deadman timeout" in What4 itself that will interrupt the solver if it does not voluntarily abort at the designated goal timeout period.
* Modifications to solver error handling to pop frames if possible, but not fail if the solver is not functional enough to allow frame popping.
* …
=> Enhance timeout handling

.github/workflows/test.yml
The boolector 3.2.2 version causes test failures in the adapter tests
for what4.  This nixos version pin retains boolector 3.2.1 (at least
for now).
=> [CI] use nixos-21.05 for GHC 9 tests for boolector 3.2.1

what4/src/What4/Expr/VarIdentification.hs, what4/src/What4/ProblemFeatures.hs
for tracking the use of uninterpreted and defined functions.
Use these to enhance the information collected in `VarIdentification`.
=> Add `ProblemFeature` values

what4/src/What4/Protocol/VerilogWriter/ABCVerilog.hs
Variable names generated by `safeSymbol` can include exclamation marks.
Otherwise, they're guaranteed to be safe variable names in most
languages. Here, we replace `!` with `_` in any names before generating
the final Verilog text.
=> Fix syntax errors in Verilog variable names

what4-abc/src/What4/Solver/ABC.hs, what4/src/What4/Expr/App.hs, what4/src/What4/Expr/AppTheory.hs, what4/src/What4/Expr/Builder.hs, what4/src/What4/Expr/GroundEval.hs, what4/src/What4/Interface.hs, what4/src/What4/InterpretedFloatingPoint.hs, what4/src/What4/Protocol/SMTLib2.hs, what4/src/What4/Protocol/SMTWriter.hs, what4/src/What4/Protocol/VerilogWriter/Backend.hs, what4/src/What4/Solver/Yices.hs, what4/src/What4/SpecialFunctions.hs, what4/what4.cabal
Implement a uniform representation for special functions on real and floating-point values.  We still have very limited solver support for these functions, but this allows us to at least represent the majority of the operation appearing in, e.g., `math.h`.
=> Special functions

what4/src/What4/LabeledPred.hs
`LabeledPred` already has `Bifoldable`, `Bitraversable`, and `Show{1,2}` instances, but for some reason, it does not have `Foldable`, `Traversable`, or `Show` instances. I believe this to be an oversight, which this patch corrects.
=> Add missing Foldable, Traversable, and Show instances for LabeledPred

.github/workflows/test.yml
Previous CI was just installing the latext nix version, which broke when switching from 2.3 to 2.4 due to cmdline syntax changes.
Also ensured that both library and includes for zlib package are present and available for the build process.
Switched to use newer nix commands and syntax, and use cabal.project.local file to ensure zlib installation can be utilized.
=> CI update to lock nix version

what4/CHANGES.md, what4/src/What4/BaseTypes.hs, what4/src/What4/Expr/App.hs, what4/src/What4/Expr/ArrayUpdateMap.hs, what4/src/What4/Expr/BoolMap.hs, what4/src/What4/Expr/MATLAB.hs, what4/src/What4/Expr/StringSeq.hs, what4/src/What4/Expr/UnaryBV.hs, what4/src/What4/Expr/WeightedSum.hs, what4/src/What4/Interface.hs, what4/src/What4/InterpretedFloatingPoint.hs, what4/src/What4/SemiRing.hs, what4/src/What4/SpecialFunctions.hs, what4/src/What4/Utils/OnlyIntRepr.hs
This was prompted by GaloisInc/parameterized-utils#126, but the changes needed on `what4`'s end can be applied independently.
=> Allow building with `hashable-1.4.*`

what4/CHANGES.md, what4/src/What4/Protocol/SMTLib2.hs, what4/src/What4/Protocol/SMTLib2/Syntax.hs
GHC will claim `forall` as a keyword, so this is a preemtive fix.
`exists` is changed to maintain a consistent naming convention.
Fixes #166
=> Rename the `forall` and `exists` operators to `forall_` and `exists_`

what4-transition-system/test/Main.hs, what4/README.md, what4/doc/QuickStart.hs, what4/src/What4/Expr.hs, what4/test/AdapterTest.hs, what4/test/ExprBuilderSMTLib2.hs, what4/test/ExprsTest.hs, what4/test/IteExprs.hs, what4/test/OnlineSolverTest.hs, what4/test/TestTemplate.hs
define a new dummy data type that can be used for the
expression builder state field.
=> Export some additional operations from `What4.Expr`

what4/src/What4/Protocol/SMTWriter.hs, what4/test/ExprBuilderSMTLib2.hs
Doing so will cause the integers to be rendered with decimals (e.g., `0.0` instead of `0`). While some solvers are OK with such integers, CVC4 is picky and will reject integers with decimal places, as seen in #182. The fix is straightforward: just use `integerTerm` instead of `rationalTerm . fromInteger`.
Fixes #182.
=> Don't use `rationalTerm` when ground-evaluating integers

what4/CHANGES.md, what4/src/What4/Expr/App.hs, what4/src/What4/Interface.hs, what4/src/What4/Utils/ResolveBounds/BV.hs, what4/test/ExprBuilderSMTLib2.hs, what4/what4.cabal
This adds two functions whose functionality are technically separate, but are useful when used in combination with each other. `resolveSymBV` uses an online SMT solver to query the `BVDomain` (i.e., the lower and upper version bounds) of a `SymBV` in situations where `{un,}signedBVBounds` won't suffice. At that point, `unsafeSetAbstractValue` can be used to manually set the `AbstractValue` of a symbolic expression—or, in the case of `SymBV`, manually set the `BVDomain`. I have used this in a downstream project with moderate success, and since the underlying machinery could be applicable in other situations, I thought it worth upstreaming to `what4`.
I have added test cases for both functions to ensure that they behave as expected.
=> Add `unsafeSetAbstractValue` and `resolveSymBV`

what4/src/What4/Protocol/SMTLib2.hs, what4/test/ExprBuilderSMTLib2.hs
Previously, we were too liberal with the characters we would emit
without escaping, and we would incorrectly fail to escape `\` characters
if they had a following `u` character.  In addition, our unescaping routine
was incorrectly rejecting strings from solvers if they ended with a literal
`\` character.
Fixes #184
Fixes #185
=> Fix some issues with string escaping/unescaping in the SMTLib2 writer

.github/workflows/gen_matrix.pl, .github/workflows/test.yml, README.md, what4/test/ExprBuilderSMTLib2.hs, what4/test/OnlineSolverTest.hs
Runs tests using various fixed versions of the supported solvers.
This now runs all tests against specific revisions of solvers, and will let us expand the set of revisions in the future as needed.  For many of the solvers, this also establishes a "lower limit" to the supported version; if it was important to show support for earlier versions of any of these solvers we could do so, but it would mean additional controls over which tests were run, and so that didn't seem worth it at the present time unless specific needs can be identified.
Overall, this will help us maintain a compatibility matrix and also identify any regressions that occur in the future.
=> Fix solver versions

.github/workflows/gen_matrix.pl, .github/workflows/test.yml, what4-abc/what4-abc.cabal, what4-blt/what4-blt.cabal, what4-transition-system/what4-transition-system.cabal, what4/CHANGES.md, what4/src/Test/Verification.hs, what4/src/What4/SemiRing.hs, what4/test/GenWhat4Expr.hs
This contains a variety of changes needed to make the libraries in the `what4` compile warning-free with GHC 9.2:
* GHC 9.2 includes `-Woperator-whitespace-ext-conflict` as a part of `-Wall`, which causes `Test.Verification` to warn when built with GHC 9.2. The fix is simple: just add spaces after certain uses of the `$` character.
* GHC 9.2 includes `-Wincomplete-uni-patterns` as a part of `-Wall`, which causes `GenWhat4Expr` to warn when built with GHC 9.2. I fixed the warnings by introducing new `from{Bool,Int,BV8,BV16,BV32,BV64}TestExpr` functions to extract the payloads of different `TestExpr` constructors. This is no less partial than before, but at least this way any accidental partiality will result in a more descriptive error message than `Non-exhaustive patterns in ...`.
* In …
=> Allow building with GHC 9.2

what4/test/ExprBuilderSMTLib2.hs, what4/test/ExprsTest.hs, what4/test/HH/VerifyBindings.hs, what4/test/IteExprs.hs, what4/test/hedgehog/Test/Tasty/Hedgehog/Alt.hs, what4/what4.cabal
This fixes #195—or, at the very least, makes the deprecation warnings that arise from `tasty-hedgehog`'s version of `testProperty` go away. The "real" fix would be to convert every use of `testProperty` into a top-level `Property` value, but given how tedious that would be, I'm disinclined to do this unless someone specifically requests it.
=> Avoid `testProperty` deprecation warnings with `tasty-hedgehog-1.2`

what4/src/What4/Expr/Builder.hs, what4/src/What4/Interface.hs
and for obtaining the original, unannotated term from an annotation.
Fixes #192
Fixes #193
=> Add operations for projecting the `SymInteger` from a `SymNat`

.github/workflows/test.yml, what4/CHANGES.md, what4/src/What4/Expr/Builder.hs, what4/what4.cabal
The `data-binary-ieee754` library, which `what4` depends on, is deprecated. Fortunately, `what4` only uses this library for converting `Float`s and `Double`s to `Word`s, which is functionality that the `base` library has provided since GHC 8.2. As a result, removing the `data-binary-ieee754` dependency is straightforward.
=> Remove `data-binary-ieee754` dependency in favor of `GHC.Float`

what4/test/TestTemplate.hs
Running `hedgehog`'s `checkSequential` function alone isn't enough to cause a test suite to fail if one or more of the test cases to fail. Per a comment in the `hedgehog` source code [here](https://github.com/hedgehogqa/haskell-hedgehog/blob/3d4dde46e15ab25a10cac0deff03bae10ecacc4e/hedgehog-example/test/test.hs#L34-L42), the idiomatic way to do make a `checkSequential` failure imply test suite failure is to check the result of running `checkSequential` and, if that is `False`, throw `exitFailure`. This patch incorporates that advice into the `test_templates` test suite.
Fixes #206.
=> `template_tests`: Emit an error code if tests fail

.github/workflows/test.yml
Nix 2.4 does not work well with GitHub Actions' Ubuntu 22.04 runners, as seen in https://github.com/cachix/install-nix-action/issues/141.
-----
I'm hoping that this addresses the CI woes encountered in #226.
=> CI: Use Nix 2.11.0

what4/what4.cabal
Builds fine and all tests pass here with tasty-sugar 2.0.0.0.
=> Allow tasty-sugar 2.0+

.github/workflows/gen_matrix.pl, .github/workflows/test.yml, what4-abc/src/What4/Solver/ABC.hs, what4-abc/what4-abc.cabal, what4-blt/what4-blt.cabal, what4-transition-system/src/What4/TransitionSystem.hs, what4-transition-system/what4-transition-system.cabal, what4/CHANGES.md, what4/src/What4/Config.hs, what4/src/What4/Expr/Simplify.hs, what4/src/What4/Expr/VarIdentification.hs, what4/src/What4/Expr/WeightedSum.hs, what4/src/What4/Partial.hs, what4/src/What4/Protocol/SMTLib2.hs, what4/src/What4/Protocol/SMTLib2/Parse.hs, what4/src/What4/Protocol/SMTWriter.hs, what4/src/What4/Protocol/VerilogWriter/AST.hs, what4/src/What4/Protocol/VerilogWriter/Backend.hs, what4/src/What4/Serialize/Parser.hs, what4/src/What4/Serialize/Printer.hs, what4/what4.cabal
This patch contains a variety of fixes needed to build the libraries in the
`what4` repo with GHC 9.6:
* GHC 9.6 bundles `mtl-2.3.*`, which no longer re-exports `Control.Monad`,
`Control.Monad.IO.Class`, and similar modules from `mtl`-related modules.
To accommodate this, various imports have been made more explicit.
* `MonadTrans t` now has a quantified `forall m. Monad m => Monad (t m)`
superclass in `mtl-2.3.*`. As a result, the `MonadTrans (PartialT sym)`
instance must now have an `IsExpr (SymExpr sym)` instance context in order
for it to typecheck, as this is the same instance context that `PartialT`'s
`Monad` instance has.
This is technically a breaking change, so I have noted it in the `what4`
changelog. That being said, this change is unlikely to affect many people
in practice, …
=> Support building with GHC 9.6

what4/src/What4/Utils/Versions.hs, what4/what4.cabal
`versions-6.0.*` removes the `VChunk` data type, which `what4` defines an orphan `Lift` instance for. This requires some CPP to fix up. This is somewhat messy, and in an ideal world, we'd move these orphan instances directly to the `versions` library. (See also https://github.com/fosskers/versions/issues/68.)
Fixes #240.
=> Allow building with `versions-6.0.*`

what4/src/What4/Utils/Versions.hs, what4/what4.cabal
`versions-6.0.2` introduces a `Lift Version` instance, which finally allows us to delete the ugly, CPP'd mess of orphan instances that we define in `What4.Utils.Versions`.
Related to #240.
=> Require `versions >= 6.0.2`

what4/src/What4/Expr/Builder.hs, what4/src/What4/Interface.hs
Fixes #244. Should result in slightly better performance for code that annotates bound variables, and prettier printing.
=> what4: Don't annotate bound variables

what4/src/What4/Expr/Builder.hs
Remove the `arrayIte` simplification because it actually increases expression size, and combined with the muxing from the memory model can create very large expressions.
=> More simplifications

.github/workflows/gen_matrix.pl, .github/workflows/test.yml, what4-abc/what4-abc.cabal, what4-blt/what4-blt.cabal, what4-transition-system/what4-transition-system.cabal, what4/src/What4/Protocol/SMTLib2.hs, what4/test/AdapterTest.hs, what4/test/ConfigTest.hs, what4/test/ProbeSolvers.hs
This patch contains a variety of fixes needed to build the libraries in the `what4` repo with GHC 9.8:
* Bump the upper version bounds on `base` and `text` to allow building with the versions that are bundled with GHC 9.8 (`base-4.19.*` and `text-2.1.*`, respectively).
* Replace uses of `head` and `tail` (which trigger `-Wx-partial` warnings with GHC 9.8) with total functions or `panic`s, depending on what is appropriate.
* Bump the `aig` submodule to bring in the changes from GaloisInc/aig#16 and GaloisInc/aig#17.
=> Allow building with GHC 9.8

.github/workflows/lint.yml, .hlint.yaml, what4/src/What4/Expr/App.hs, what4/src/What4/Expr/Builder.hs, what4/src/What4/Expr/MATLAB.hs, what4/src/What4/Interface.hs, what4/test/ExprBuilderSMTLib2.hs, what4/test/InvariantSynthesis.hs
Fixes #257. The HLint configuration only checks that these helpers are used where appropriate. I used it to find places where they would be useful. It may also serve as a template for downstream repos. I added HLint checking to CI as well.
=> Add `bv{Zero,One}` helpers, hlint config

what4/CHANGES.md, what4/src/What4/Expr.hs, what4/src/What4/Expr/Builder.hs, what4/src/What4/Protocol/SMTLib2.hs, what4/test/AdapterTest.hs
Add `pushMuxOps` and `pushMuxOpsOption`. If this option is enabled, What4 will push certain `ExprBuilder` operations (e.g., `zext`) down to the branches of `ite` expressions. In some (but not all) circumstances, this can result in operations that are easier for SMT solvers to reason about.
=> Guard mux-pushing simplifications behind option

.github/workflows/gen_matrix.pl, what4/src/What4/Solver/CVC4.hs, what4/src/What4/Solver/CVC5.hs, what4/test/ExprBuilderSMTLib2.hs
Due to a bug in CVC4 (https://github.com/cvc5/cvc5/issues/3402), the What4 bindings to CVC4 avoid user-defined datatypes and instead use CVC4's built-in `Tuple` datatype. This same `Tuple` workaround was applied to the CVC5 bindings (added in https://github.com/GaloisInc/what4/pull/204), but they don't really work properly, as CVC4 and CVC5 use completely different syntaxes for tuples. See https://github.com/GaloisInc/what4/issues/265.
We could attempt to update the CVC5 bindings to use the modern tuple syntax, but this is somewhat non-trivial, as the syntax for 1-tuples changed in `cvc5-1.0.9` from `Tuple` to `UnitTuple` (see https://github.com/cvc5/cvc5/pull/10012). As such, we would have to generate different code for different versions of CVC5, which would be unpleasant.
Thankfully, …
=> CVC5: Don't use Tuple workaround when declaring structs

what4/CHANGES.md, what4/what4.cabal
A new Hackage release is needed as part of a fix for https://github.com/GaloisInc/crucible/issues/1246.
=> 1.6.1 release prep

.github/workflows/test.yml, what4/what4.cabal
This ensures that the GHC versions listed in `what4.cabal` are in sync with what is actually tested in the CI.
=> Update `tested-with` versions

.github/workflows/gen_matrix.pl, .github/workflows/test.yml, what4-abc/what4-abc.cabal, what4-blt/what4-blt.cabal, what4-transition-system/what4-transition-system.cabal, what4/src/What4/Expr/BoolMap.hs, what4/src/What4/Expr/WeightedSum.hs, what4/src/What4/Solver/CVC5.hs, what4/src/What4/Utils/AnnotatedMap.hs, what4/src/What4/Utils/Environment.hs, what4/src/What4/Utils/Word16String.hs, what4/test/InvariantSynthesis.hs, what4/what4.cabal
`base-4.20` (GHC 9.10) re-exports `foldl'` from the `Prelude`, which conflicts with the `foldl'` function defined in `What4.Utils.Word16String`. To avoid conflicts, we re-export `What4.Utils.Word16String.foldl'` using a qualified export, which avoids warnings in a backwards-compatible fashion.
We also fix a variety of `-Wunused-imports` warnings caused by the same change and add GHC 9.10.1 to CI.
Fixes https://github.com/GaloisInc/what4/issues/272.
=> Support building with GHC 9.10

what4/test/OnlineSolverTest.hs
=> Disable timeout test for CVC4 1.8

what4/CHANGES.md, what4/src/What4/Protocol/SMTLib2.hs
this avoids issues where the solver process was
killed via `What4.Protocol.Online.killSolver`
(e.g. due to a forced timeout)
=> SMTLib2: only send exit command if solver process is active

what4/CHANGES.md, what4/src/What4/Protocol/SMTLib2.hs, what4/test/OnlineSolverTest.hs, what4/what4.cabal
This backports the bugfix from #288 to the `1.6` branch, which will form the basis for a new minor Hackage release of `what4` (1.6.3).
=> Backport #288 changes to new minor release (1.6.3)

.github/workflows/test.yml
We already cache `${{ steps.setup-haskell.outputs.cabal-store }}`, so caching the store this way was likely redundant. Not sure why `packages` was cached, but it's probably unnecessary.
Also, in cabal-3.12 or later, the cache is written to ~/.local/state/cabal/store (to respect the XDG Base Directory Specification), so ~/.cabal/store will be flat-out wrong at that point.
Fixes #291.
=> ci: Stop caching `~/.cabal/{packages,store}`

.github/workflows/test.yml
Previously, this refered to a nonexistent `step`. Fixes #300.
=> ci: Fix caching of Cabal store

what4/src/What4/Protocol/SMTLib2/Parse.hs, what4/src/What4/Solver/DReal.hs, what4/src/What4/Utils/Streams.hs, what4/what4.cabal
It was only used for decoding `ByteString`s, which `Text` can do.
=> what4: Remove dependency on utf8-string

what4/CHANGES.md, what4/src/What4/Expr/Builder.hs
When building terms with uninterpreted functions, we'd like to only make a new uninterpreted function once per symbol.
As such, we need to keep track of which symbols we've already processed.   The `ExpreBuilder` has such a cache for when it translates things to uninterpreted functions.  However, for user defined uninterpreted functions we were using a completely separate cache.
I can't think of a good reason to keep these two separate, so this PR exposes the `IORef` for the cache, which makes
it easier to reuse in other contexts that also need to user uninterpreted functions.
To makes things compatable we slightly tweak the type of the cache, but it is essentially the same as it was before.
=> Expose uninterpreted functions cache

.github/dependabot.yml
We have previously manually bumped the pinned versions of the actions used in our CI workflows. Let's automate this process using Dependabot. With this configuration, Dependabot will check for updates weekly, and open pull requests for each of them.
Benefits:
- Save maintainer time when updates are push-button
- See benefits from updated dependencies more quickly and reliably
Risks:
- Requires maintainers to review and merge more PRs
- May create noise for updates that aren't push-button and require some manual intervention
I think our experience using Dependabot on parameterized-utils justifies integrating it here. We've had 3 PRs so far over a period of a few months, and each was merged quickly and without manual intervention.
Fixes #317.
=> ci: Use Dependabot for weekly bumps to pinned GitHub Actions

what4/CHANGES.md, what4/src/What4/Concrete.hs, what4/src/What4/Concretize.hs, what4/src/What4/Expr/GroundEval.hs, what4/src/What4/Interface.hs, what4/src/What4/Utils/ResolveBounds/BV.hs, what4/what4.cabal
=> Concretization and unique concretization
